= https://jit.o3.ru/browse/MPMT-2843[Предпросмотр в ЛК показа фото в Catalog]
:toc:
:toc-title:         Содержание

== Проблема

=== Контекст

Запланирован переход всех контейнеров на сайте ozon.ru на соотношение сторон 3х4.
После перехода появится много товаров, у которых соотношение сторон главного фото будет не соответствовать рекомендациям маркетплейса.
Продавец внутри карточки не видит и не имеет информации, как его фотография выглядит в каталоге т.к. некоторые изображенимя масштабируются по методу 8 точек, что не видно в личном кабинете.


=== Алгоритм показа главного фото и текст информера

1. Если соотношение сторон у загруженной картинки 3х4, то оно вписывается в контейнер - дополнительных текстов не даем (указываем что это главное фото)

2. Если соотношение сторон у загруженной картинки не 3х4, но оно подходит под растягивание по методу 8 точек - растягиваем чтобы вписывалось в контейнер. Дополнительно появляется информер с текстом "Так будет выглядеть главное фото в каталоге. Мы растянем его к верхней и нижней границе. Используйте изображение формата 3х4, чтобы в кадр вошли все важные детали."

3. Если соотношение сторон у загруженной картинки не 3х4, и оно не подходит под растягивание по методу 8 точек - вписываем в контейнер как есть, показывая поля сверху и снизу. Дополнительно появляется информер с текстом "Так будет выглядеть главное фото в каталоге. Используйте изображение формата 3х4, чтобы ваш товар смотрелся выигрышно."

=== Критерии готовности

- Селлеру доступен предпросмотр главного фото в том виде, в котором оно отображается в каталоге (с полями или увеличенное по методу 8 точек к верхней и нижней границе).
- Селлеру доступен информер, сообщающий о том, что фото в каталоге будут выглядеть аналогично отображению в предпросмотре

== Решение

=== Где выполнять метод 8 точек

Выполнять метод 8 точек на бекенде каждый раз, когда у селлера в ЛК обновляется главное фото, слишком затратно и ведёт к внезапно прыгающему интерфейсу. По этой причине следует выполнять данный метод на фронтенде, где время на его выполнение будет в пределах 10мс (а, скорее всего, даже в пределах 1мс), вместо сотен мс.

Функционал нужен только для того, чтобы селлер лучше представлял как будет выглядеть его фото в каталоге, если оно подойдёт под критерии масштабирования 8 точек. Ни бекенд ни взаимодействие с ним никак не меняется. На бекенд будет отправляться то же самое оригинальное изображение без масштабирования.

=== Алгоритм расчёта метода 8 точек

Алгортим взят из задачи https://jit.o3.ru/browse/CONTENTMP-23845

Координаты точек:

- {0,0} - левая верхняя
- {x\2,0} - средняя верхняя
- {x,0} - правая верхняя
- {x,y/2} - правая средняя
- {x,y} - правая нижняя
- {x/2,y} - средняя нижняя
- {0,y} - левая нижняя
- {0,y/2} - левая средняя
- где x - ширина, y - высота картинки в px, если x ИЛИ y нечетное, то при x\2 округляем в большую сторону

- Если у фотографии < 4 точек имеют цвет #FFFFFF, то фотографию необходимо растянуть (cover)
- Если у фотографии >= 4 точек имеют цвет #FFFFFF, тто фотографию необходимо вместить (contain)

Значения cover или contain принимают CSS свойства object-fit и background-size, в зависимости от метода показа изображения.

=== Инструмент для выполнения

1. Используем встроенный инструмент <canvas>, создаваемый через document.createElement('canvas'). Хватит двумерного контекста getContext('2d'). Необходимо поместить его на верхнем уровне заранее, чтобы не создавать множество контекстов при каждом расчёте.

2. Для получения трёх цветов по координатам используем метод контекста getImageData(x, y, 1, 1), где x,y - координаты точки. Как результат получаем объект ImageData, свойство data которого содержит Uint8ClampedArray, который представляет собой массив чисел 0-255, соответствующий значениям RGBA этого пикселя. Если RGB === [255, 255, 255], то данное значение будет аналогичным hex #FFFFFF (то есть будет являться белым цветом).

